services:
  sql-mariadb:
    image: mariadb
    ports:
      - "6000:3306"
    environment:
      - MARIADB_USER=victor
      - MARIADB_PASSWORD=victor123
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=learning-sql
    volumes:
      - mariadb_volume:/var/lib/mysql

volumes: 
  mariadb_volume:
