name: learning-mongodb

services:
  my-mongo:
    image: mongo
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=victor
      - MONGO_INITDB_ROOT_PASSWORD=vitoadm
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:

#mongo --host 127.0.0.1:27017 -p vitoadm -u victor
